### ISSUE TITLE
Bump php version?

### ISSUE THREAD

**Issue by Chris53897** [FriendsOfSymfony/FOSCKEditorBundle#234] opened 2021-10-06 20:42 UTC
Hi. Is there any interest to bump php version to ^7.4|^8.0" as supported Versions. https://php.watch/versions
I could do the PR

**Comment by 0x6d6c** [comment] 2022-01-29 14:46
Support for **PHP 8.0** has been added in #223. Possible duplicate of #222.

**Comment by lsmith77** [comment] 2024-01-23 15:31
fixed via https://github.com/FriendsOfSymfony/FOSCKEditorBundle/pull/258

**Closed as completed by lsmith77** 2024-01-23 15:31 UTC
