### ISSUE TITLE
CKEditor 5 support

### ISSUE THREAD

**Issue by napestershine** [FriendsOfSymfony/FOSCKEditorBundle#210] opened 2020-01-14 11:16 UTC
Hi

Thanks for this awesome bundle

is it possible to get support for CKEditor 5?

Thanks

**Comment by haivala** [comment] 2020-03-23 07:45
Has someone investigated this?
I installed the frontend part from 5 but it did not work at all.

**Comment by cedricplaire** [comment] 2020-04-07 19:49
the file structure is not the same, I am currently looking for a simple solution. otherwise, I would wait for this beautiful team to update its bundle

**Comment by zoomtronic** [comment] 2020-06-04 15:02
@cedricplaire  did you manage to get Ckeditor 5 working ?

**Comment by lsmith77** [comment] 2020-12-24 10:30
duplicate of https://github.com/FriendsOfSymfony/FOSCKEditorBundle/issues/94

**Closed by lsmith77** 2020-12-24 10:30 UTC
